#pragma once
#define MACRO_XPLUM_AUTO_INIT_OBJECT_INSTANCE(PARAM01_ITC_TYPE, PARAM02_ITC_NAME, PARAM03_ITC_INIT_PARAM...) PARAM01_ITC_TYPE PARAM02_ITC_NAME = PARAM01_ITC_TYPE(PARAM03_ITC_INIT_PARAM)
#define MACRO_XPLUM_AUTO_INIT_REFERENCE_VALUE(PARAM01_REFER_NAME, PARAM02_VALUE_NAME) decltype(PARAM02_VALUE_NAME) &PARAM01_REFER_NAME = PARAM02_VALUE_NAME
#define MACRO_XPLUM_AUTO_INIT_REFERENCE_ARRAY(PARAM01_REFER_NAME, PARAM02_ARRAY_NAME) std::remove_all_extents<decltype(PARAM02_ARRAY_NAME)>::type(&PARAM01_REFER_NAME)[sizeof(PARAM02_ARRAY_NAME) / sizeof(*PARAM02_ARRAY_NAME)] = PARAM02_ARRAY_NAME
