#pragma once

#define MACRO_XPLUM_TRACE_PREFIX
#if (false)
#undef MACRO_XPLUM_TRACE_PREFIX
#define MACRO_XPLUM_TRACE_PREFIX "file://"
#endif

#define MACROxEXPANSIONxLEVEL00_MACRO_XPLUM_TRACE_FILE_LINE(PARAM01_FILE, PARAM02_LINE) MACRO_XPLUM_TRACE_PREFIX PARAM01_FILE ":" #PARAM02_LINE
#define MACROxEXPANSIONxLEVEL01_MACRO_XPLUM_TRACE_FILE_LINE(PARAM01_FILE, PARAM02_LINE) MACROxEXPANSIONxLEVEL00_MACRO_XPLUM_TRACE_FILE_LINE (PARAM01_FILE, PARAM02_LINE)
#define MACROxEXPANSIONxLEVEL02_MACRO_XPLUM_TRACE_FILE_LINE MACROxEXPANSIONxLEVEL01_MACRO_XPLUM_TRACE_FILE_LINE (__FILE__, __LINE__)
#define MACRO_XPLUM_TRACE_FILE_LINE MACROxEXPANSIONxLEVEL02_MACRO_XPLUM_TRACE_FILE_LINE
